"""Create Proposal table

Revision ID: bbea157c5c30
Revises: 194d59c51e72
Create Date: 2023-09-27 14:23:17.853605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbea157c5c30'
down_revision = '194d59c51e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposal')
    # ### end Alembic commands ###
